### ISSUE TITLE
feistest: Mundlak Test

### ISSUE THREAD

**Issue by georgeblck** [ruettenauer/feisr#5]
Hello and thank your for this interesting package. 

I am looking for a nice R-function to calculate the Mundlak Test and it seems to me that your `feistest()` is doing just that.
However, I do not really understand the Description in the help provided Documentation. I learned that the Mundlak Test is done through testing if the person-specific averages - estimated with RE- of the time-varying variables are zero (with a Wald-Test). [See this description.](https://blog.stata.com/2015/10/29/fixed-effects-or-random-effects-the-mundlak-approach/)

I know that there is another way of getting the same result: including the centered variables and the person-specific averages. And then testing if they are the same.

So my question is: Which one of the *type* options in the feistest function correspond to the Mundlak-Test? 

Thanks in advance for any help.

**Comment by ruettenauer** [comment]
Hi georgeblck,

Actually, all the three types in `feistest()` perform a Mundlak-Test. However, the `type="art1"` and `type="art3"` are extensions of the conventional Mundlak test, as they test for heterogenous slopes (focusing on the person-specific predicted values instead of person-specific averages).

So, the test described in your link is similar to the conventional Mundlak test, comparing FE and RE. This is done by `type="art2"`. Here we include the original variable and the person-specific averages, and test whether the coefficients for the averages differ from zero (by Wald test).

For more information on the three test types have a look at our working paper: [https://osf.io/preprints/socarxiv/k4rnu/](https://osf.io/preprints/socarxiv/k4rnu/)

Hope that helps, Tobias

**Comment by georgeblck** [comment]
Hello Tobias,

thank you for your answer! And the package!
